Drop support of HTTPlug 1.x
apigee/apigee-client-php pull request #106
Opened 2020-10-12 15:21 UTC by mxr576

Closes #41

2020-10-12 15:24 UTC, mxr576 commented on composer.json
> +        "php-http/discovery": "^1.6.0",
Because: https://github.com/php-http/discovery/blob/1.6.0/CHANGELOG.md#160---2019-01-23

2020-10-12 15:30 UTC, mxr576 commented on composer.json
> +        "symfony/property-access": "^3.4.41 || ^4.4.9",
Because https://github.com/symfony/property-access/commit/e1a6c91c0007e45bc1beba929c76548ca9fe8a85

2020-11-05 12:59 UTC, mxr576 commented
@arshad @arlina-espinoza @cnovak hi, may I get a review on this? These are old dependencies and having them here blocks upstream projects to depend on newer, supported versions if they would like to use them together with this library.

2020-11-09 19:09 UTC, arlina-espinoza requested changes
@mxr576 When trying to install with the latest template for Kickstart (https://github.com/apigee/devportal-kickstart-project-composer/blob/8.x/composer.json), I get the following errors:

```console
arlina@system76:/v/w/h/c/d9$ composer require apigee/apigee-client-php:"dev-issue/41 as 2.0.6" --update-with-dependencies
./composer.json has been updated
Loading composer repositories with package information                                              Updating dependencies (including require-dev)         
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install apigee/apigee-client-php 2.0.6|remove php-http/guzzle6-adapter v1.1.1
    - Conclusion: install apigee/apigee-client-php 2.0.6
    - Conclusion: don't install php-http/httplug 2.2.0
    - apigee/apigee-client-php 2.0.6 requires php-http/client-implementation ^1.0 -> satisfiable by php-http/guzzle6-adapter[v1.1.1].
    - Conclusion: don't install php-http/guzzle6-adapter v1.1.1
    - Conclusion: remove php-http/httplug v1.1.0
    - Conclusion: don't install php-http/httplug 2.1.0
    - Installation request for apigee/apigee-client-php dev-issue/41 as 2.0.6 -> satisfiable by apigee/apigee-client-php[dev-issue/41].
    - Installation request for drupal/apigee_m10n (locked at 1.7.0, required as ^1.0.0) -> satisfiable by drupal/apigee_m10n[1.7.0].
    - php-http/guzzle6-adapter v1.1.1 requires php-http/httplug ^1.0 -> satisfiable by php-http/httplug[v1.1.0, v1.0.0, v1.0.0-RC1, v1.0.0-alpha, v1.0.0-alpha2, v1.0.0-alpha3, v1.0.0-beta].
    - Can only install one of: php-http/httplug[v1.1.0, 2.x-dev].
    - Can only install one of: php-http/httplug[2.x-dev, v1.1.0].
    - Can only install one of: php-http/httplug[v1.0.0, 2.x-dev].
    - Can only install one of: php-http/httplug[v1.0.0-RC1, 2.x-dev].
    - Can only install one of: php-http/httplug[v1.0.0-alpha, 2.x-dev].
    - Can only install one of: php-http/httplug[v1.0.0-alpha2, 2.x-dev].
    - Can only install one of: php-http/httplug[v1.0.0-alpha3, 2.x-dev].
    - Can only install one of: php-http/httplug[v1.0.0-beta, 2.x-dev].
    - apigee/apigee-client-php 2.0.6 requires php-http/httplug ^2.0 -> satisfiable by php-http/httplug[2.1.0, 2.2.0, 2.x-dev, v2.0.0].
    - Conclusion: don't install php-http/httplug v2.0.0


Installation failed, reverting ./composer.json to its original content.
```

Looking into what other dependencies are locking php-http/httplug to ^1.0, I find:

```console
arlina@system76:/v/w/h/c/d9$ composer why php-http/httplug -t
php-http/httplug v1.1.0 HTTPlug, the HTTP client abstraction for PHP
├──apigee/apigee-client-php 2.0.5 (requires php-http/httplug ^1.1)
│  ├──apigee/devportal-kickstart-project (requires apigee/apigee-client-php dev-issue/41 as 2.0.6)
│  ├──drupal/apigee_edge 1.18.0 (requires apigee/apigee-client-php ^2.0.4)
│  │  ├──apigee/apigee_devportal_kickstart 1.21.0 (requires drupal/apigee_edge ^1.16)
│  │  │  └──apigee/devportal-kickstart-project (requires apigee/apigee_devportal_kickstart ^1.0.0)
│  │  └──drupal/apigee_m10n 1.7.0 (requires drupal/apigee_edge ^1.16)
│  │     └──apigee/devportal-kickstart-project (requires drupal/apigee_m10n ^1.0.0)
│  └──drupal/apigee_m10n 1.7.0 (requires apigee/apigee-client-php ~2.0.3)
│     └──apigee/devportal-kickstart-project (requires drupal/apigee_m10n ^1.0.0)
├──php-http/client-common 1.10.0 (requires php-http/httplug ^1.1)
│  └──apigee/apigee-client-php 2.0.5 (requires php-http/client-common ^1.9)
│     ├──apigee/devportal-kickstart-project (requires apigee/apigee-client-php dev-issue/41 as 2.0.6)
│     ├──drupal/apigee_edge 1.18.0 (requires apigee/apigee-client-php ^2.0.4)
│     │  ├──apigee/apigee_devportal_kickstart 1.21.0 (requires drupal/apigee_edge ^1.16)
│     │  │  └──apigee/devportal-kickstart-project (requires apigee/apigee_devportal_kickstart ^1.0.0)
│     │  └──drupal/apigee_m10n 1.7.0 (requires drupal/apigee_edge ^1.16)
│     │     └──apigee/devportal-kickstart-project (requires drupal/apigee_m10n ^1.0.0)
│     └──drupal/apigee_m10n 1.7.0 (requires apigee/apigee-client-php ~2.0.3)
│        └──apigee/devportal-kickstart-project (requires drupal/apigee_m10n ^1.0.0)
└──php-http/guzzle6-adapter v1.1.1 (requires php-http/httplug ^1.0)
   └──drupal/apigee_edge 1.18.0 (requires php-http/guzzle6-adapter ^1.1.1)
      ├──apigee/apigee_devportal_kickstart 1.21.0 (requires drupal/apigee_edge ^1.16)
      │  └──apigee/devportal-kickstart-project (requires apigee/apigee_devportal_kickstart ^1.0.0)
      └──drupal/apigee_m10n 1.7.0 (requires drupal/apigee_edge ^1.16)
         └──apigee/devportal-kickstart-project (requires drupal/apigee_m10n ^1.0.0)

```

So it seems that to drop support for HTTPlug 1.x we would also need to require the 2.x from the `apigee_edge` module. Does this sound right to you?

2020-11-10 06:09 UTC, mxr576 commented
@arlina-espinoza yes it does, just `php-http/guzzle6-adapter v1.1.1` has to be bumped to ^2.0, that is all.

2020-11-29 23:27 UTC, arlina-espinoza approved these changes
LGTM, created https://github.com/apigee/apigee-edge-drupal/pull/525 to support it from the `drupal/apigee_edge` side.

2020-11-29 23:27 UTC, merged