Apigee hybrid /organizations call does not allow expand=true.
apigee/apigee-client-php pull request #114
Opened 2020-12-17 06:11 UTC by giteshk

Fixed how organizations are fetched for Apigee Hybrid.

2020-12-20 16:45 UTC, mxr576 requested changes

2020-12-20 16:45 UTC, mxr576 commented on src/Api/Management/Controller/OrganizationController.php
> +        return $this->responseArrayToArrayOfEntities($responseArray);
Can't we just use the following logic instead?

```
if (ClientInterface::HYBRID_ENDPOINT == $this->client->getEndpoint()) {
  // Do the custom stuff and return
}

return parent::getEntities(); // parent is the inherited method from the trait.

```

You may need to alias the inherited trait methods for this.

2020-12-20 16:46 UTC, mxr576 commented
>Apigee hybrid ... does not allow expand=true

only here or on other API (entity) endpoints too? IIRC this is not the first Hybrid workaround for expand=true. 

#87 
#91

2020-12-23 00:24 UTC, cnovak commented
Thanks much for your excellent code review @mxr576 . It looks like this should be changed to follow the patterns that @mxr576 pointed out.

2022-03-15 15:53 UTC, closed without merging