End of support for PHP 7.4
apigee/apigee-client-php pull request #239
Opened 2023-01-31 13:11 UTC by shishir-intelli

Closes #235
End of support for PHP 7.4 and Added PHP 8.2 on GitHub-action test.

2023-02-06 09:07 UTC, shishir-intelli commented
Rolled back PHP 8.2  GitHub action test due to  league/period library compatibility issue with PHP 8.2
Created separate issue here https://github.com/apigee/apigee-client-php/issues/240

2023-03-08 14:34 UTC, mxr576 commented on composer.json
> +        "php": "^8.0",
Be more specific about actually supported (and tested) PHP versions.

See: https://github.com/apigee/apigee-edge-drupal/pull/816


```suggestion
        "php": "~8.0.0 || ~8.1.0",
```

2023-03-08 15:07 UTC, giteshk requested changes
Please hold off on this change.

2023-06-06 13:28 UTC, giteshk approved these changes

2023-06-13 13:17 UTC, giteshk commented
We are ready to end support for 7.4 with the latest changes for AppGroup needing PHP 8.0 minimum

2023-06-13 13:37 UTC, merged