DRUP-420 : Add docstore API integration to Apigee Client for PHP library
apigee/apigee-client-php pull request #33
Opened 2018-11-21 21:00 UTC by giteshk

Allows the ability to interact with the Docstore apis. 
Docstore is only available on-cloud today.

2018-11-22 09:52 UTC, mxr576 commented
No offense, but I do not get how this code passed on the code style to be honest, probably the code style checker requires some adjustments ;)
* variable names should be snakeCase
* At least variable type hint should be added to the class properties, one new line between each property.
* All entity and controller classes should have an interface defined that describes its public behaviors - this is something that we can not validate with static code analyses at this moment.

2018-11-22 12:09 UTC, mxr576 requested changes

2018-11-22 12:09 UTC, mxr576 commented on src/Api/Docstore/Serializer/DocstoreSerializer.php
> +     * CollectionSerializer constructor.
Outdated doc block comment.

2018-11-22 12:09 UTC, mxr576 commented on src/Api/Docstore/Controller/DocstoreController.php
> +class DocstoreController extends EntityController
Please create an interface for this controller and move all public method definitions to that.

2018-11-22 12:09 UTC, mxr576 commented on src/Api/Docstore/Controller/DocstoreController.php
> +            ($entity instanceof Doc ? 'specs/new' : 'folders'),
Let's separate this logic to dedicated createFolder() and createSpec() methods. Controller methods should serve only one purpose.

2018-11-22 12:09 UTC, mxr576 commented on src/Api/Docstore/Controller/DocstoreController.php
> +        $entity->setEtag($response->getHeader('ETag')[0]);
The entity serializer should be the one that parses _all_ information from an API response and creates/updates an entity. So etag should be set by the serializer also.

2018-11-22 12:09 UTC, mxr576 commented on src/Api/Docstore/Controller/DocstoreController.php
> +     * Upload a openAPI file to the backend.
s/openApi/OpenAPI/g

2018-11-22 12:09 UTC, mxr576 commented on src/Api/Docstore/Controller/DocstoreController.php
> +     * This will change in the future
Missing dot.

2018-11-22 12:09 UTC, mxr576 commented on src/Api/Docstore/Controller/DocstoreController.php
> +     * Always returns application/json
Missing dot.

2018-11-22 12:09 UTC, mxr576 commented on src/Api/Docstore/Controller/DocstoreController.php
> +    private function parseDocstoreResponse(ResponseInterface $response): DocstoreObject
This is the task of an entity serializer and not a controller. Precisely the denormalizers inside an entity serializer should decide what object they return based on an API response. Please remove this logic here.

2018-11-22 12:09 UTC, mxr576 commented on src/Api/Docstore/Entity/Collection.php
> +class Collection extends \Apigee\Edge\Api\Docstore\Entity\DocstoreObject
Do not use FQCN.

2018-11-22 12:09 UTC, mxr576 commented on src/Api/Docstore/Entity/Collection.php
> +class Collection extends \Apigee\Edge\Api\Docstore\Entity\DocstoreObject
Are you sure that this is an actual entity and not just a structure?

2018-11-22 12:09 UTC, mxr576 commented on src/Api/Docstore/Entity/Collection.php
> +    protected $kind = 'Collection';
As I can see there 1:1 relationship between the "kind" and the class so there is no need to store the kind as property in object - especially it should not be defined in all sub classes of the DocsStore class - rather the denormalizer could use the "kind" information from the API response to create an object with a proper type and the normalizer could add this information (property) to the API request payload based on the type of the normalized class before it gets sent to Apigee Edge. (See Rate plans as an example.)

2018-11-22 12:09 UTC, mxr576 commented on src/Api/Docstore/Entity/Doc.php
> +     * url to fetch the spec file.
Sentence starts with a capital letter.

2018-11-22 12:09 UTC, mxr576 commented on src/Api/Docstore/Entity/DocstoreObject.php
> +    use \Apigee\Edge\Entity\CommonEntityPropertiesAwareTrait;
Do not use FQCN.

2018-11-22 12:09 UTC, mxr576 commented on src/Api/Docstore/Entity/DocstoreObject.php
> +    protected $permissions;
Missing typehint from properties, some of them may deserve a description as well.

2018-11-22 12:09 UTC, mxr576 commented on src/Api/Docstore/Entity/DocstoreObject.php
> +    public function getIsTrashed()
This is a boolean property so its getter should `isTranshed()` and it setter should be `setTrashed()`. 
See Address' name converter as an example for how you can fix this:
https://github.com/apigee/apigee-client-php/blob/2.x/src/Api/Monetization/NameConverter/AddressNameConverter.php#L31
https://github.com/apigee/apigee-client-php/blob/2.x/src/Api/Monetization/Denormalizer/AddressDenormalizer.php#L41
https://github.com/apigee/apigee-client-php/blob/2.x/src/Api/Monetization/Normalizer/AddressNormalizer.php#L41
https://github.com/apigee/apigee-client-php/blob/2.x/src/Api/Monetization/Structure/Address.php#L29

2018-11-22 12:09 UTC, mxr576 commented on src/Api/Docstore/Entity/DocstoreObject.php
> +abstract class DocstoreObject extends Entity
Please define an interface for this class, move all its public definition to that class and please define interfaces for all its subclasses as well.

2018-11-22 12:09 UTC, mxr576 commented on tests/Api/Docstore/Controller/DocstoreControllerTest.php
> + * @group management
This test does not belong to a management API test, this is what this group stands for. I'd rather introduce a new `docstore`.

2018-11-22 12:09 UTC, mxr576 commented on tests/Api/Docstore/Controller/DocstoreControllerTest.php
> +        $homeFolder = static::entityController()->load('/homeFolder');
Why `/` is necessary? It should not be. `load()` method on an entity controller loads an entity by id.

2018-11-22 12:09 UTC, mxr576 commented on tests/Api/Docstore/Controller/DocstoreControllerTest.php
> +        static::removeTestData();
Feel free to inline the method content's here. It seems that you only use this in one place.

2018-11-22 12:09 UTC, mxr576 commented on src/Api/Docstore/Controller/DocstoreController.php
> +        $uri = $this->getEntityEndpointUri($entity->id());
Unnecessary new variable `$uri`, you only use it in one place.

2018-11-22 12:09 UTC, mxr576 commented on src/Api/Docstore/Controller/DocstoreController.php
> +        $update_arr = [];
Use camelCase variable names inside the PHP API Client.

2018-11-22 12:09 UTC, mxr576 commented on src/Api/Docstore/Controller/DocstoreController.php
> +            $this->getEntitySerializer()->serialize($update_arr, 'json'),
Can't you pass the entity directly to the serializer that should generate the required request payload from it? If not, why?

2018-11-22 12:09 UTC, mxr576 commented on src/Api/Docstore/Controller/DocstoreController.php
> +            $this->getHeaders() + ['Accept' => 'application/json, text/plain, */*']);
Isn't only "application/json" what this API can return? If not "text/plan" could be acceptable if the API returns a JSON file with incorrect content type, but I do not understand why "*/*" is necessary. Basically it means we accept anything, although our serializer can only read JSON.

2018-11-22 12:09 UTC, mxr576 commented on src/Api/Docstore/Controller/DocstoreController.php
> +     * Docstore entity id start with a "/".
Entity ids should not start with `/`. Just add that to the path builder...
https://github.com/apigee/apigee-client-php/blob/8017c3993ab78c239744b4b1fdd25deebf61678b/src/Api/Management/Controller/DeveloperAppCredentialController.php#L67

2018-11-22 12:09 UTC, mxr576 commented on src/Api/Docstore/Entity/Collection.php
> +class Collection extends \Apigee\Edge\Api\Docstore\Entity\DocstoreObject
What could be in a collection? Folders? Docs? Can they be mixed or only from the same type? If the answer is one type per collection then I think you should introduce new FolderCollection and DocCollection classes.

2018-11-30 19:12 UTC, giteshk commented on src/Api/Docstore/Controller/DocstoreController.php
> +            $this->getEntitySerializer()->serialize($update_arr, 'json'),
The patch method only takes certain values. I tried passing the entire entity and it fails.

2018-11-30 19:19 UTC, giteshk commented on src/Api/Docstore/Controller/DocstoreController.php
> +            $this->getHeaders() + ['Accept' => 'application/json, text/plain, */*']);
This is the actual openAPI specification that is uploaded in edge.

The API documentation had that in the instructions. But I have tested this with application/json and my tests ran. So I am setting this to only be application/json

2018-11-30 19:25 UTC, giteshk commented on src/Api/Docstore/Controller/DocstoreController.php
> +     * Docstore entity id start with a "/".
Entity ID returned by the backend API is in this format "/c3Rvc-ZG9j-93459"

The logic to generate the entity URL is abstracted in this one method.

2018-12-10 21:15 UTC, giteshk commented on src/Api/Docstore/Entity/Collection.php
> +class Collection extends \Apigee\Edge\Api\Docstore\Entity\DocstoreObject
Collection is the object that is returned when you pull in contents from any folder

2018-12-10 21:20 UTC, giteshk commented on tests/Api/Docstore/Controller/DocstoreControllerTest.php
> +        $homeFolder = static::entityController()->load('/homeFolder');
entity id's for all docstore entities begin with a "/"

2018-12-10 23:16 UTC, giteshk commented on src/Api/Docstore/Entity/Collection.php
> +    protected $kind = 'Collection';
Need this when running the create operation on the docstore entities.

Either I do this or have to set the kind in the constructor when I initialize it.

2018-12-10 23:17 UTC, giteshk commented on src/Api/Docstore/Entity/DocstoreObject.php
> +    public function getIsTrashed()
I implemented this. 

BTW the trashed flag will always return false. There is no concept of Trash in docstore as it stands today.  I think they might implement this in the future.

2018-12-11 00:09 UTC, giteshk commented
I think there was a merge issue. I will close this and create a new pull request.

2018-12-11 00:09 UTC, closed without merging