Add 8.3 version support of PHP
apigee/apigee-client-php pull request #368
Opened 2024-06-18 11:41 UTC by kedarkhaire

Fixes #367

2024-06-18 11:44 UTC, mxr576 requested changes

2024-06-18 11:44 UTC, mxr576 commented on composer.json
> +        "php": "~8.1 || ~8.2 || ~8.3",
No tests were executed on PHP 8.3 via GHA :exclamation:

2024-06-18 11:53 UTC, kedarkhaire commented on composer.json
> +        "php": "~8.1 || ~8.2 || ~8.3",
Added

2024-06-24 15:57 UTC, kedarkhaire commented
Closing for wrong forked

2024-06-24 15:57 UTC, closed without merging