[#65] Deprecate "createdBy" and "lastModifiedBy" properties
apigee/apigee-client-php pull request #74
Opened 2019-10-25 16:57 UTC by arlina-espinoza

Closes #65 . Deprecate "createdBy" and "lastModifiedBy" properties, as they are not being used by the Drupal Edge module, and are not supported by Hybrid.
This PR adds deprecation comments and removes the properties from the test mock data as well.

2019-10-25 17:18 UTC, mxr576 requested changes
Just because these properties are deprecated I would not remove them from the JSON files and the tests because non-hybrid orgs still support them and we should have test coverage for these.

2019-10-25 17:18 UTC, mxr576 commented on src/Entity/CommonEntityPropertiesAwareTrait.php
> +     * @deprecated Not used in Hybrid orgs.
Can we used a similar, standardized format like Drupal 8 introduced which tells a deveoper which version XY was deprecated and when it will be removed? Also, if there is any replacement for the class/method/etc a developer can get information about it?

https://github.com/drupal/core/blob/b3273887e822d745ed277ce36cd07dc56e795d83/includes/file.inc#L49

2019-10-25 20:16 UTC, arlina-espinoza commented
> Just because these properties are deprecated I would not remove them from the JSON files and the tests because non-hybrid orgs still support them and we should have test coverage for these.

You are right, I've added them back.

2019-10-25 20:24 UTC, arlina-espinoza commented on src/Entity/CommonEntityPropertiesAwareTrait.php
> +     * @deprecated Not used in Hybrid orgs.
I've changed it to:

```
@deprecated in 2.0.4, will be removed before 3.0.0. Unsupported in Hybrid.
@see https://github.com/apigee/apigee-client-php/issues/65
```

_2.0.4 should be the next release._

2019-10-29 21:25 UTC, minnur approved these changes
This looks good to me. TravisCI is failing, looks like it is not related to this PR.

2019-10-30 14:17 UTC, mxr576 commented on src/Entity/CommonEntityPropertiesAwareTrait.php
> +     * @deprecated Not used in Hybrid orgs.
> Unsupported in Hybrid.

What does it mean exactly? What happens if I call these methods on an object returned from a hybrid org? Do they return an empty string?

2019-10-30 19:17 UTC, arlina-espinoza commented on src/Entity/CommonEntityPropertiesAwareTrait.php
> +     * @deprecated Not used in Hybrid orgs.
@mxr576 The fields are empty so calling the methods would return NULL, as they are never initialized.

2019-10-30 19:18 UTC, merged